"""create travel_goals table

Revision ID: 65f9c24ceff1
Revises:
Create Date: 2026-08-14 18:52:42.376352
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65f9c24ceff1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "travel_goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_travel_goals")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("travel_goals")
    # ### end Alembic commands ###
